import { Info } from '../SSASubtitle';

const HEADER_ORDER = [
  'ScriptType', 'Title', 'Collisions', 'PlayResY', 'PlayResX', 'WrapStyle',
];

const scriptInfoSerializer = (info: Info) => {
  let scriptInfoSection = `[Script Info]
; Subtitle generated by AlmAnime`;

  scriptInfoSection += HEADER_ORDER.reduce((section, header) => `${section}
${header}: ${(info as { [key: string]: string | number })[header]}`, '');

  const additonalFields = Object.entries(info)
    .sort(([a], [b]) => a.localeCompare(b))
    .reduce((section, [key, value]) => {
      if (HEADER_ORDER.includes(key)) {
        return section;
      }

      return `${section}
${key}: ${value}`;
    }, '');

  if (additonalFields) {
    scriptInfoSection += `
; The following fields are not specified in the specs, but here they are${additonalFields}`;
  }

  scriptInfoSection += `
`;

  return scriptInfoSection;
};

export default scriptInfoSerializer;
