import { Info } from '../SSASubtitle';

const scriptInfoSerializer = (info: Info) => `[Script Info]
; Subtitle generated by AlmAnime
ScripType: ${info.ScriptType}
Title: ${info.Title}
Collisions: ${info.Collisions}
PlayResY: ${info.PlayResY}
PlayResX: ${info.PlayResX}
WrapStyle: ${info.WrapStyle}
; The following fields are not specified in the specs, but here they are
Last Style Storage: ${info['Last Style Storage']}
ScaledBorderAndShadow: ${info.ScaledBorderAndShadow}
Video Aspect Ratio: ${info['Video Aspect Ratio']}
Video File: ${info['Video File']}
Video Position: ${info['Video Position']}
Video Zoom: ${info['Video Zoom']}
`;

export default scriptInfoSerializer;
