version: '3'

services:
  alm-ui:
    container_name: alm-ui
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "18"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity