name: On new release
on: 
  workflow_dispatch:
    inputs:
      nextRelease:
        description: 'Next Release'     
        required: true
        default: 'patch'
        type: choice
        options: 
        - major
        - minor
        - patch
        - prerelease
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Automated Version Bump
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'v'
          version-type: ${{ inputs.nextRelease }}
      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ inputs.nextRelease == 'prerelease' }} 
          tag_name: ${{ steps.bump_version.outputs.newTag }}